# Workflow de CI para a Aplicação NestJS

name: NestJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Usando uma versão LTS do Node.js
        cache: 'npm'

    - name: Instalar dependências
      run: npm ci # 'npm ci' é mais rápido e seguro para CI

    - name: Executar migrações do banco de dados
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
      run: npm run migration:run

    - name: Construir a aplicação
      run: npm run build

    # Você pode adicionar um passo para testes aqui se tiver testes configurados
    # - name: Executar testes
    #   run: npm test
