# Workflow de CI para a Aplicação NestJS

name: NestJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Adiciona um diretório de trabalho padrão para todos os comandos
    defaults:
      run:
        working-directory: ./nexus-rifa

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: nexus-rifa/package-lock.json # Caminho para o cache

    - name: Instalar dependências
      run: npm install # Usando 'npm install' para evitar erro de package-lock.json ausente

    - name: Executar migrações do banco de dados
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
      run: npm run migration:run

    - name: Construir a aplicação
      run: npm run build
